"""ajout colonne photo a la table eleves

Revision ID: a2abb0cd4f56
Revises: aedfc4c81948
Create Date: 2026-09-05 18:47:20.206703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2abb0cd4f56'
down_revision: Union[str, Sequence[str], None] = 'aedfc4c81948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eleves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('prenom', sa.String(), nullable=True),
    sa.Column('matricule', sa.String(), nullable=True),
    sa.Column('sexe', sa.String(), nullable=True),
    sa.Column('cycle', sa.String(), nullable=True),
    sa.Column('classe_id', sa.Integer(), nullable=True),
    sa.Column('tuteur', sa.String(), nullable=True),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('type_reduction', sa.String(), nullable=True),
    sa.Column('montant_reduction', sa.Float(), nullable=True),
    sa.Column('document_justificatif', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eleves_id'), 'eleves', ['id'], unique=False)
    op.create_index(op.f('ix_eleves_matricule'), 'eleves', ['matricule'], unique=True)
    op.create_index(op.f('ix_eleves_nom'), 'eleves', ['nom'], unique=False)
    op.create_index(op.f('ix_eleves_prenom'), 'eleves', ['prenom'], unique=False)
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('devise', sa.String(length=255), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('contacts', sa.String(length=255), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('date_expiration', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_schools_id'), 'schools', ['id'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('stacktrace', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_id'), 'system_logs', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('derniere_activite', sa.DateTime(), nullable=True),
    sa.Column('changer_mdp_requis', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('enseignant_id', sa.Integer(), nullable=True),
    sa.Column('eleve_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.ForeignKeyConstraint(['enseignant_id'], ['enseignants.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('annees_scolaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annees_scolaires_id'), 'annees_scolaires', ['id'], unique=False)
    op.create_index(op.f('ix_annees_scolaires_libelle'), 'annees_scolaires', ['libelle'], unique=False)
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(), nullable=True),
    sa.Column('niveau', sa.String(), nullable=True),
    sa.Column('cycle', sa.String(), nullable=True),
    sa.Column('capacite', sa.Integer(), nullable=True),
    sa.Column('frais_scolarite', sa.Float(), nullable=True),
    sa.Column('frais_inscription', sa.Float(), nullable=True),
    sa.Column('frais_transport', sa.Float(), nullable=True),
    sa.Column('frais_cantine', sa.Float(), nullable=True),
    sa.Column('frais_coges', sa.Float(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_id'), 'classes', ['id'], unique=False)
    op.create_index(op.f('ix_classes_libelle'), 'classes', ['libelle'], unique=False)
    op.create_table('depenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('cycle', sa.String(length=50), nullable=False),
    sa.Column('libelle', sa.String(length=200), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('categorie', sa.String(length=100), nullable=False),
    sa.Column('date_depense', sa.DateTime(), nullable=True),
    sa.Column('auteur', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('echeances_paiements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(), nullable=True),
    sa.Column('montant_attendu', sa.Float(), nullable=True),
    sa.Column('date_limite', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_echeances_paiements_id'), 'echeances_paiements', ['id'], unique=False)
    op.create_table('enseignants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('prenom', sa.String(), nullable=True),
    sa.Column('specialite', sa.String(), nullable=True),
    sa.Column('qualite', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('volume_horaire', sa.Float(), nullable=True),
    sa.Column('classes_attribuees', sa.String(), nullable=True),
    sa.Column('matieres_attribuees', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enseignants_id'), 'enseignants', ['id'], unique=False)
    op.create_index(op.f('ix_enseignants_nom'), 'enseignants', ['nom'], unique=False)
    op.create_index(op.f('ix_enseignants_prenom'), 'enseignants', ['prenom'], unique=False)
    op.create_table('journal_activites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('module', sa.String(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('valeur_avant', sa.Text(), nullable=True),
    sa.Column('valeur_apres', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_activites_id'), 'journal_activites', ['id'], unique=False)
    op.create_table('matieres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('coefficient', sa.Float(), nullable=True),
    sa.Column('cycle', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matieres_id'), 'matieres', ['id'], unique=False)
    op.create_index(op.f('ix_matieres_libelle'), 'matieres', ['libelle'], unique=False)
    op.create_table('paiements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('reference_recu', sa.String(), nullable=True),
    sa.Column('eleve_id', sa.Integer(), nullable=True),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('mode_reglement', sa.String(), nullable=True),
    sa.Column('motif', sa.String(), nullable=True),
    sa.Column('nom_payeur', sa.String(), nullable=True),
    sa.Column('contact_payeur', sa.String(), nullable=True),
    sa.Column('agent_caisse', sa.String(), nullable=True),
    sa.Column('date_paiement', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paiements_id'), 'paiements', ['id'], unique=False)
    op.create_index(op.f('ix_paiements_reference_recu'), 'paiements', ['reference_recu'], unique=True)
    op.create_table('presences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('eleve_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('motif', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presences_id'), 'presences', ['id'], unique=False)
    op.create_table('programmes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('code_matiere', sa.String(), nullable=True),
    sa.Column('nom_matiere', sa.String(), nullable=True),
    sa.Column('coefficient', sa.Float(), nullable=True),
    sa.Column('volume_horaire', sa.Float(), nullable=True),
    sa.Column('semestre', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programmes_code_matiere'), 'programmes', ['code_matiere'], unique=False)
    op.create_index(op.f('ix_programmes_id'), 'programmes', ['id'], unique=False)
    op.create_table('affectations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('enseignant_id', sa.Integer(), nullable=True),
    sa.Column('classe_id', sa.Integer(), nullable=True),
    sa.Column('matiere_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['enseignant_id'], ['enseignants.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affectations_id'), 'affectations', ['id'], unique=False)
    op.create_table('cahiers_texte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('classe_id', sa.Integer(), nullable=True),
    sa.Column('matiere_id', sa.Integer(), nullable=True),
    sa.Column('enseignant_username', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('contenu_realise', sa.String(), nullable=True),
    sa.Column('difficultees', sa.String(), nullable=True),
    sa.Column('mesures_correctives', sa.String(), nullable=True),
    sa.Column('duree', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['enseignant_username'], ['users.username'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cahiers_texte_id'), 'cahiers_texte', ['id'], unique=False)
    op.create_table('emplois_du_temps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('classe_id', sa.Integer(), nullable=True),
    sa.Column('classe', sa.String(), nullable=True),
    sa.Column('jour', sa.String(), nullable=True),
    sa.Column('heure', sa.String(), nullable=True),
    sa.Column('matiere', sa.String(), nullable=True),
    sa.Column('enseignant', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emplois_du_temps_id'), 'emplois_du_temps', ['id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('eleve_id', sa.Integer(), nullable=True),
    sa.Column('matiere_id', sa.Integer(), nullable=True),
    sa.Column('valeur', sa.Float(), nullable=True),
    sa.Column('trimestre', sa.String(), nullable=True),
    sa.Column('type_evaluation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.create_table('planification_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('classe_id', sa.Integer(), nullable=True),
    sa.Column('matiere_id', sa.Integer(), nullable=True),
    sa.Column('type_evaluation', sa.String(), nullable=True),
    sa.Column('periode', sa.String(), nullable=True),
    sa.Column('date_eval', sa.Date(), nullable=True),
    sa.Column('horaire', sa.String(), nullable=True),
    sa.Column('coefficient', sa.Integer(), nullable=True),
    sa.Column('salle', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planification_evaluations_id'), 'planification_evaluations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_planification_evaluations_id'), table_name='planification_evaluations')
    op.drop_table('planification_evaluations')
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_emplois_du_temps_id'), table_name='emplois_du_temps')
    op.drop_table('emplois_du_temps')
    op.drop_index(op.f('ix_cahiers_texte_id'), table_name='cahiers_texte')
    op.drop_table('cahiers_texte')
    op.drop_index(op.f('ix_affectations_id'), table_name='affectations')
    op.drop_table('affectations')
    op.drop_index(op.f('ix_programmes_id'), table_name='programmes')
    op.drop_index(op.f('ix_programmes_code_matiere'), table_name='programmes')
    op.drop_table('programmes')
    op.drop_index(op.f('ix_presences_id'), table_name='presences')
    op.drop_table('presences')
    op.drop_index(op.f('ix_paiements_reference_recu'), table_name='paiements')
    op.drop_index(op.f('ix_paiements_id'), table_name='paiements')
    op.drop_table('paiements')
    op.drop_index(op.f('ix_matieres_libelle'), table_name='matieres')
    op.drop_index(op.f('ix_matieres_id'), table_name='matieres')
    op.drop_table('matieres')
    op.drop_index(op.f('ix_journal_activites_id'), table_name='journal_activites')
    op.drop_table('journal_activites')
    op.drop_index(op.f('ix_enseignants_prenom'), table_name='enseignants')
    op.drop_index(op.f('ix_enseignants_nom'), table_name='enseignants')
    op.drop_index(op.f('ix_enseignants_id'), table_name='enseignants')
    op.drop_table('enseignants')
    op.drop_index(op.f('ix_echeances_paiements_id'), table_name='echeances_paiements')
    op.drop_table('echeances_paiements')
    op.drop_table('depenses')
    op.drop_index(op.f('ix_classes_libelle'), table_name='classes')
    op.drop_index(op.f('ix_classes_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_annees_scolaires_libelle'), table_name='annees_scolaires')
    op.drop_index(op.f('ix_annees_scolaires_id'), table_name='annees_scolaires')
    op.drop_table('annees_scolaires')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_logs_id'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_schools_id'), table_name='schools')
    op.drop_table('schools')
    op.drop_index(op.f('ix_eleves_prenom'), table_name='eleves')
    op.drop_index(op.f('ix_eleves_nom'), table_name='eleves')
    op.drop_index(op.f('ix_eleves_matricule'), table_name='eleves')
    op.drop_index(op.f('ix_eleves_id'), table_name='eleves')
    op.drop_table('eleves')
    # ### end Alembic commands ###
